controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_homepage:
    path: /
    controller: App\Controller\HomepageController::number

app_signup:
    path: /signup
    controller: App\Controller\SecurityController::signup

app_signin:
    path: /signin
    controller: App\Controller\SecurityController::signin

app_signout:
    path: /signout
    controller: App\Controller\SecurityController::signout

app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

app_dashboard_table:
    path: /dashboard/table
    controller: App\Controller\DashboardController::getReservations

app_reserve_lake:
    path: /reserve_lake
    controller: App\Controller\LakeReservationController::reserveLake

app_reserve_lake_check:
    path: /reserve_lake_check
    controller: App\Controller\LakeReservationController::checkLake

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_admin_table:
    path: /admin/table
    controller: App\Controller\AdminController::getAllReservations

app_admin_delete_reservation:
    path: /admin/delete_reservation/{reservationId}
    controller: App\Controller\AdminController::deleteReservation